# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];

    initrd.kernelModules = [];

    kernelModules = [];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5f7d9dbb-c1cc-49b5-b7f9-b81e2d801aa4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5128d97a-0e1d-4b52-a214-55dfbdd6f07d".device = "/dev/disk/by-uuid/5128d97a-0e1d-4b52-a214-55dfbdd6f07d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BDDD-8650";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/68b97239-90cd-4cea-95b6-2d4ab9f835b5";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
