-- FIXME: monitors
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1", default = true, on_created_empty = "kitty" })
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1", on_created_empty = "vikunja-desktop" })
hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1", on_created_empty = "thunderbird" })
hl.workspace_rule({ workspace = "4", monitor = "HDMI-A-1", on_created_empty = "vesktop" })
hl.workspace_rule({ workspace = "5", monitor = "HDMI-A-1", on_created_empty = "keepassxc" })
hl.workspace_rule({ workspace = "6", monitor = "DP-1", default = true, on_created_empty = "firefox" })
hl.workspace_rule({ workspace = "7", monitor = "DP-1" })
hl.workspace_rule({ workspace = "8", monitor = "DP-1" })
hl.workspace_rule({ workspace = "9", monitor = "DP-1" })
hl.workspace_rule({ workspace = "10", monitor = "DP-1" })
hl.workspace_rule({ workspace = "11", monitor = "DP-3", default = true, on_created_empty = "cider" })
