on: [push]
name: Dead code analysis
jobs:
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
