on: [push]

name: Lint Nix code

jobs:
  statix:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.1.0
        - uses: cachix/install-nix-action@v22
        - uses: cachix/cachix-action@v12
          with:
            name: statix
        - uses: jocelynthode/statix-action@master
